ALTER TABLE menu_items ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE menu_items ADD COLUMN size TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN protein TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN conditions TEXT NOT NULL DEFAULT '';
